apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: a-deploy
  name: a-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: a-deploy
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: a-deploy
    spec:
      containers:
        - image: "{{ .Values.image }}"
          name: "{{ .Values.image }}"
